// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrztgmqukiyevaotfjgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyenRnbXF1a2l5ZXZhb3RmamdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNjQ5MDEsImV4cCI6MjA2MTg0MDkwMX0.ONFVI9k1_ufB4iWmmNx78QuP9lQAm6gtHlGn78l56vQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);